### ISSUE TITLE
CT Maximum call stack size exceeded

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-on-a-string#153]
```
wave-on-a-string : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/wave-on-a-string/wave-on-a-string_en.html?continuousTest=%7B%22test%22%3A%5B%22wave-on-a-string%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663649316066%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at (Transform3.js:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (AlignBox.ts:1:0)
at (AlignBox.ts:1:0)
at (LayoutConstraint.ts:1:0)
at (AlignBox.ts:1:0)
at (AlignBox.ts:1:0)
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

wave-on-a-string : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/wave-on-a-string/wave-on-a-string_en.html?continuousTest=%7B%22test%22%3A%5B%22wave-on-a-string%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663656401168%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at (TinyEmitter.ts:1:0)
at (Transform3.js:1:0)
at (Transform3.js:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (AlignBox.ts:1:0)
at (AlignBox.ts:1:0)
at (LayoutConstraint.ts:1:0)
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM

----------------------------------

wave-on-a-string : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663642258128/wave-on-a-string/wave-on-a-string_en.html?continuousTest=%7B%22test%22%3A%5B%22wave-on-a-string%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1663642258128%22%2C%22timestamp%22%3A1663669183703%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at (Node.ts:1:0)
at (TinyEmitter.ts:1:0)
at (Transform3.js:1:0)
at (Transform3.js:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (Node.ts:1:0)
at (AlignBox.ts:1:0)
at (AlignBox.ts:1:0)
id: Bayes Puppeteer
Snapshot from 9/19/2022, 8:50:58 PM
```

**Comment by jonathanolson** [comment]
Thanks for finding! Likely is related to layout (I'll create an issue to link)

**Comment by jonathanolson** [comment]
@KatieWoe should be fixed above, can you confirm?
