### ISSUE TITLE
CT validation failed: value failed isValidValue: 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-on-a-string#154]
```
wave-on-a-string : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664504553731/phet-io-wrappers/state/?sim=wave-on-a-string&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22wave-on-a-string%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664504553731%22%2C%22timestamp%22%3A1664510528702%7D
Uncaught Error: Uncaught Error: Assertion failed: validation failed:
value failed isValidValue: -100,-91.68418090340182,-83.11697062357393,-74.82043108934344,-33.11796266745654,6.976372849268441,41.60989865285709,74.85378593635666,36.69303232174346,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664504553731/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (StateSchema.ts:207:8)
at checkStateObjectValid (IOType.ts:421:42)
at isStateObjectValid (IOType.ts:461:9)
at validateStateObject (IOType.ts:298:23)
at toStateObject (WOASModel.js:522:28)
at toStateObject (IOType.ts:285:32)
at toStateObject (PhetioStateEngine.ts:118:48)
at getValueJSON (PhetioStateEngine.ts:176:33)
id: Bayes Puppeteer
Snapshot from 9/29/2022, 8:22:33 PM

----------------------------------

wave-on-a-string : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664504553731/phet-io-wrappers/state/?sim=wave-on-a-string&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22wave-on-a-string%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664504553731%22%2C%22timestamp%22%3A1664526765186%7D
Uncaught Error: Uncaught Error: Assertion failed: validation failed:
value failed isValidValue: -100,-98.42159732356266,-96.8432591096029,-95.26588782803468,-93.68870988263865,-92.11346465555663,-90.53854148461105,-88.96651452648297,-87.39493808840832,-85.8272179243231,-84.26007638609946,-82.69774661234214,-81.13612311044065,-79.58026116148096,-78.02523256931048,-76.47690849280413,-74.92954419627101,-73.38981943766169,-71.8511801204311,-70.32110631872982,-68.79224275876284,-67.27286055506295,-65.7548124339882,-64.24715029425934,-62.74094502112141,-61.24601807480416,-44.96778374612603,-29.29310219762969,-14.359363822367495,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664504553731/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (StateSchema.ts:207:8)
at checkStateObjectValid (IOType.ts:421:42)
at isStateObjectValid (IOType.ts:461:9)
at validateStateObject (IOType.ts:298:23)
at toStateObject (WOASModel.js:522:28)
at toStateObject (IOType.ts:285:32)
at toStateObject (PhetioStateEngine.ts:118:48)
at getValueJSON (PhetioStateEngine.ts:176:33)
id: Bayes Puppeteer
Snapshot from 9/29/2022, 8:22:33 PM

----------------------------------

wave-on-a-string : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664504553731/studio/?sim=wave-on-a-string&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22wave-on-a-string%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1664504553731%22%2C%22timestamp%22%3A1664527232289%7D
Uncaught Error: Uncaught Error: Assertion failed: validation failed:
value failed isValidValue: 100.00000000000003,77.68890373865669,56.09838212306239,35.20978828623661,15.028373959617955,-4.476438110344294,-23.287462983728762,-41.44717257640214,-58.926482440304234,-75.77971178308138,-91.96592213771778,-107.55121329404717,-108.21528062432269,-108.87420245155516,-109.52631873461289,-110.17245580348894,-110.81080613359586,-111.4423547212132,-112.06516290528148,-112.68035967857654,-113.2858931444601,-113.88302010359729,-114.46959468690103,-115.04698388872552,-115.61296842271854,-116.16900692322416,-116.71282783987529,-117.24596192786792,-117.7661075195159,-118.27484730108974,-118.76987194650074,-119.25279529497087,-119.72132337312094,-120.17708023508513,-120.61780996184712,-121.04512603602225,-121.45683304437311,-121.85451337792716,-122.23605408402277,-122.60298644744361,-122.95330119358341,-123.288459223997,-123.60657518989008,-123.90902129342267,-124.19405516802611,-124.46294317363005,-124.71410358133126,-124.94868113353496,-125.16527080391883,-125.36488149415091,-125.54629917607753,-125.71038440156677,-125.85612650922143,-125.98422705508791,-126.0938890570378,-126.18564640282061,-126.25892392943811,-126.31408126352983,-126.35077094060891,-126.36917388738327,-126.36917388738327
prunedValidator:
[object Object]
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1664504553731/assert/js/assert.js:28:13)
at assert (validate.ts:25:16)
at validate (StateSchema.ts:207:8)
at checkStateObjectValid (IOType.ts:421:42)
at isStateObjectValid (IOType.ts:461:9)
at validateStateObject (IOType.ts:298:23)
at toStateObject (WOASModel.js:522:28)
at toStateObject (IOType.ts:285:32)
at toStateObject (PhetioStateEngine.ts:118:48)
at getValueJSON (PhetioStateEngine.ts:176:33)
id: Bayes Puppeteer
Snapshot from 9/29/2022, 8:22:33 PM
```

**Comment by jonathanolson** [comment]
@samreid I'm not able to reproduce this. It looks likely to be the Float64Array string positions. Thoughts on how to reproduce/handle?
