### ISSUE TITLE
CT Assertion failed: _yDraw in state schema but not in the state object

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/wave-on-a-string#155]
```
wave-on-a-string : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1680112175334/wave-on-a-string/wave-on-a-string_en.html?continuousTest=%7B%22test%22%3A%5B%22wave-on-a-string%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1680112175334%22%2C%22timestamp%22%3A1680114975963%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: _yDraw in state schema but not in the state object
Error: Assertion failed: _yDraw in state schema but not in the state object
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1680112175334/assert/js/assert.js:28:13)
at assert (StateSchema.ts:142:32)
at Array.forEach
at forEach (StateSchema.ts:140:28)
at checkStateObjectValid (IOType.ts:403:42)
at isStateObjectValid (IOType.ts:436:9)
at validateStateObject (IOType.ts:281:23)
at toStateObject (PhetioStateEngine.ts:129:48)
at getValueJSON (PhetioStateEngine.ts:189:33)
at Array.forEach
id: Bayes Puppeteer
Snapshot from 3/29/2023, 11:49:35 AM
```

**Comment by jonathanolson** [comment]
@zepumph is there a chance that this is from the recent state refactoring?

**Comment by zepumph** [comment]
Over to @samreid about https://github.com/phetsims/tandem/issues/282

**Comment by samreid** [comment]
Fixed, @zepumph can you please spot check?

**Comment by zepumph** [comment]
Great thanks. Sorry I didn't catch it last time.
